

cache: packages

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      language: r
      r: release
    - os: linux
      dist: trusty
      language: r
      r: devel
    - os: osx
      osx_image: xcode8
      language: r
      r: release


warnings_are_errors: false

r_packages:
  - stringi
  - digest
  - devtools
  - Rcpp
  - roxygen2
  - htmltools
  - rmarkdown
  - knitr
  - testthat
  - yaml

notifications:
  email:
    on_success: change
    on_failure: change

