
language: r

cache: packages

sudo: required

dist: xenial

warnings_are_errors: false

r_packages:
  - roxygen2
  - rmarkdown
  - testthat

notifications:
  email:
    on_success: change
    on_failure: change
