

cache: packages

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      language: r
      r: release
      r_packages:
        - stringi
        - digest
        - devtools
        - Rcpp
        - roxygen2
        - htmltools
        - rmarkdown
        - knitr
        - testthat
        - yaml

    - os: linux
      dist: trusty
      language: python
      python: 3.5
#      install:
#        - pip install -r requirements.txt
      script:
        - python setup.py build

    - os: linux
      dist: trusty
      language: r
      r: devel
    - os: osx
      osx_image: xcode8
      language: r
      r: release
      r_packages:
        - stringi
        - digest
        - devtools
        - Rcpp
        - roxygen2
        - htmltools
        - rmarkdown
        - knitr
        - testthat
        - yaml


warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

