
language: r

cache: packages

sudo: false

dist: trusty

warnings_are_errors: false

r_packages:
  - devtools
  - Rcpp
  - roxygen2
  - rmarkdown
  - knitr
  - testthat

notifications:
  email:
    on_success: change
    on_failure: change

