

cache: packages

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      language: r
      r: release
# TODO Need to confirm if really unnecessary, or just getting away with it due to cache: packages
#      r_packages:
#        - stringi
#        - digest
#        - devtools
#        - Rcpp
#        - roxygen2
#        - htmltools
#        - rmarkdown
#        - knitr
#        - testthat
#        - yaml

    - os: linux
      dist: trusty
      language: r
      r: devel
      
    - os: osx
      osx_image: xcode8
      language: r
      r: release

    - os: linux
      dist: trusty
      language: python
      python: 3.5
      script:
        - python3 setup.py install
        - python3 setup.py test

    - os: osx
      osx_image: xcode8
      language: python
      python: 3.5
      script:
        - python3 setup.py install
        - python3 setup.py test

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

