
language: r

cache: packages

sudo: false

dist: xenial

warnings_are_errors: true

r_packages:
  - devtools
  - roxygen2
  - rmarkdown
  - knitr
  - testthat

notifications:
  email:
    on_success: change
    on_failure: change
